# Generated by Django 6.0.2 on 2026-03-30 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agentmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='is_deleted_for_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='is_deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.agentmessage'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['deleted_for_everyone', 'created_at'], name='core_agentm_deleted_2b842a_idx'),
        ),
        migrations.AddField(
            model_name='agentmessagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.agentmessage'),
        ),
        migrations.AddField(
            model_name='agentmessagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_message_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentmessagereaction',
            index=models.Index(fields=['message', 'emoji'], name='core_agentm_message_ee1079_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentmessagereaction',
            unique_together={('message', 'user')},
        ),
    ]
