# Generated by Django 6.0.2 on 2026-03-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentmessagereaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='voice_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
