# Generated by Django 6.0.2 on 2026-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentmessage_voice_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
