# Generated by Django 6.0.2 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agentmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
