# Generated by Django 5.2.12 on 2026-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agentmessage_is_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Modern'), ('light', 'Light Professional'), ('vibrant', 'Vibrant Neon'), ('sage', 'Sage Calm'), ('sand', 'Sandstone Soft')], default='dark', max_length=20),
        ),
    ]
