# Generated by Django 5.2.12 on 2026-04-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customuser_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_messages', to='core.customuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiassistantmessage',
            index=models.Index(fields=['user', 'created_at'], name='core_aiassi_user_id_850ac3_idx'),
        ),
    ]
