# Generated by Django 5.2.12 on 2026-04-06 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiassistantmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('alert_created', 'Alert Created'), ('alert_resolved', 'Alert Resolved'), ('detection_event', 'Detection Event'), ('drone_added', 'Drone Added'), ('drone_deployed', 'Drone Deployed'), ('drone_updated', 'Drone Updated'), ('drone_removed', 'Drone Removed'), ('recording_uploaded', 'Recording Uploaded'), ('recording_downloaded', 'Recording Downloaded'), ('recording_deleted', 'Recording Deleted'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('system_event', 'System Event')], default='system_event', max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('source', models.CharField(default='system', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='core.alert')),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='core.drone')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_securi_event_t_fe013c_idx'), models.Index(fields=['severity', 'created_at'], name='core_securi_severit_396375_idx'), models.Index(fields=['source', 'created_at'], name='core_securi_source_7ec9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recording_file', models.FileField(upload_to='stream_recordings/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='core.drone')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_stream_created_100194_idx')],
            },
        ),
    ]
