# Generated by Django 5.2.12 on 2026-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_securitysystemlog_streamrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysystemlog',
            name='event_type',
            field=models.CharField(choices=[('alert_created', 'Alert Created'), ('alert_resolved', 'Alert Resolved'), ('detection_event', 'Detection Event'), ('drone_added', 'Drone Added'), ('drone_deployed', 'Drone Deployed'), ('drone_updated', 'Drone Updated'), ('drone_removed', 'Drone Removed'), ('recording_uploaded', 'Recording Uploaded'), ('recording_downloaded', 'Recording Downloaded'), ('recording_deleted', 'Recording Deleted'), ('user_login', 'User Logged In'), ('user_logout', 'User Logged Out'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('system_event', 'System Event')], default='system_event', max_length=40),
        ),
    ]
