# Generated by Django 5.2.13 on 2026-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_livestreamcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="stream_url",
            field=models.URLField(
                blank=True, help_text="MJPEG/HTTP video stream URL", max_length=500
            ),
        ),
    ]
