# Generated by Django 5.2.13 on 2026-04-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_drone_stream_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="drone",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="updated_at",
        ),
    ]
